### PR TITLE
1000 fix empty selection in restore

### LINKED ISSUE #1000: [Bug]: Empty selection on saved snapshot cannot be restored
### What happened?

Snapshot with an empty selection on categorical variable will fail to load

### How to reproduce:

1. Run app below
2. Add filter variable "Species"
3. Unselect all species
4. Save snapshot
5. Download snapshot
6. Restore snapshot
    - Error occurs

### Sample code

```r
app <- init(
  data = teal_data(
    new_iris = iris,
    code = "new_iris <- iris"
  ),
  modules = modules(
    example_module()
  ),
  title = "App title"
)
if (interactive()) {
  shinyApp(app$ui, app$server)
}
#> Error in as.Date.default(slice[[field]]) : 
#>   do not know how to convert 'slice[[field]]' to class “Date”
```

### sessionInfo()

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

### PR DESCRIPTION
**Pull request by m7pr**
Closes #1000 

Hey, I fixed the issue with disability to load a snapshot with empty `selected` field.
This filter can now be created, saved and uploaded.

However on an upload of such filter and selection of such filter the app goes back to empty filters. Is that intended?

### CODE REVIEW

**Comment by chlebowa** [comment]
`selected = NULL` should set all values, `selected = character(0)` should set none.

**Comment by chlebowa** [comment]
`selected = NULL` should set all values, `selected = character(0)` should set none.

**Comment by m7pr** [comment]
Ok, just changed to character(0) and tested it sets filters to empty states which filter out all observations

File: R/teal_slices-store.R [hunk 1]
```diff
@@ -75,6 +75,13 @@ slices_restore <- function(file) {
             } else {
               slice[[field]]
             }
+        } else {
+          slice[[field]] <-
+            if (field == "selected") {
+              character(0)
+            } else {
+              NULL
+            }
```
Comment (averissimo) [inline R/teal_slices-store.R:84]: :heart: the simplicity of solution. 1 line suggestion, but feel free to ignore

```suggestion
          slice[[field]] <- switch(field, selected = character(0), NULL)
```

Comment (chlebowa) [reply R/teal_slices-store.R]: Don't you mean `slice[[field]] <- switch(field, "selected" = character(0), NULL)` :thinking:

**Review by averissimo — APPROVED** [review]
Great fix! :rocket: 

Solved the initial bug and tested a bunch of scenarios without being able to break.

The 1 line was broken into more :smiling_face_with_tear:

**Comment by chlebowa** [comment]
So what about `"choices"`? If an app is started with `choices = character(0)` (for whatever reason) and then a snapshot is created, on upload it will be converted to `choices = NULL`, which means something different.

Should we worry about such a case?

**Comment by m7pr** [comment]
Hey @chlebowa probably uncommon situation but I fixed the code so that it handles `character(0)` and `NULL`s separately. Also added 3 tests to verify that. Thanks for the input!
