### PR TITLE
The documentation of `check_modules_datanames()`

### LINKED ISSUE #1321: The documentation of `check_modules_datanames()` is incorrect
Follow-up on https://github.com/insightsengineering/teal/pull/1253

https://github.com/insightsengineering/teal/blob/9c6d38ce05fd6f6ce0741038a4d04106fb82ae61/R/utils.R#L113

But we are returning a list instead. Still figuring out what each of the element means so can't make a suggestion right now

https://github.com/insightsengineering/teal/blob/9c6d38ce05fd6f6ce0741038a4d04106fb82ae61/R/utils.R#L138-L162

### PR DESCRIPTION
**Pull request by gogonzo**
Closes #1321 
Little refurnishment:
- splitted `check_modules_datanames` to two functions, one to return `character` and other to return `shiny.tag.list`
- Renamed related utilities to better fit to what they do.

### CODE REVIEW

**Review by averissimo — COMMENTED** [review]
Nice cleanup of the code! :+1: 

Just a few minor comments.

I tried to see if the recursive function would perform better as an iterative call, but they both run in the order of `<1ms` with the difference being negligible and attributed to the assertions (that are done over and over again)

File: R/utils.R [hunk 1]
```diff
@@ -122,76 +122,124 @@ report_card_template <- function(title, label, description = NULL, with_filter,
...
+      lapply(modules$children, check_modules_datanames_recursive, datanames = datanames),
+      recursive = FALSE
+    )
   } else {
-    TRUE
+    missing_datanames <- setdiff(modules$datanames, c("all", datanames))
+    if (length(missing_datanames)) {
+      list(list(
+        label = modules$label,
+        dataname = modules$datanames,
```
Comment (averissimo) [inline R/utils.R:218]: Typo, I believe this element is never used though. (see other comment)

```suggestion
        datanames = modules$datanames,
```

File: R/utils.R [hunk 2]
```diff
@@ -122,76 +122,124 @@ report_card_template <- function(title, label, description = NULL, with_filter,
...
+                  tags$span(
+                    to_html_code_list(mod$datanames),
+                    tags$span(".", .noWS = "outside"),
+                    .noWS = c("outside")
+                  )
+                )
+              )
+            } else {
+              tags$span("No datasets are available in data.")
+            }
```
Comment (averissimo) [inline R/utils.R:194]: The messages are different between text & HTML.

This corrects the problem and makes them equivalent.

```suggestion
            if (length(datanames) >= 1) {
              tagList(
                tags$span(if (length(datanames) > 1) "Datasets" else "Dataset"),
                tags$span("available in data:"),
                tagList(
                  tags$span(
                    to_html_code_list(datanames),
                    tags$span(".", .noWS = "outside"),
                    .noWS = c("outside")
                  )
                )
              )
            } else {
              tags$span("No datasets are available in data.")
            }
```

File: R/utils.R [hunk 3]
```diff
@@ -122,76 +122,124 @@ report_card_template <- function(title, label, description = NULL, with_filter,
...
+      check_datanames,
+      function(mod) {
+        tagList(
+          tags$span(
+            tags$span(`if`(length(mod$missing_datanames) > 1, "Datasets", "Dataset")),
+            to_html_code_list(mod$missing_datanames),
+            tags$span(
+              paste0(
+                `if`(length(mod$missing_datanames) > 1, "are missing", "is missing"),
+                `if`(show_module_info, sprintf(" for tab '%s'.", mod$label), ".")
```
Comment (averissimo) [inline R/utils.R:177]:
```suggestion
            tags$span(if (length(mod$missing_datanames) > 1) "Datasets" else "Dataset"),
            to_html_code_list(mod$missing_datanames),
            tags$span(
              paste0(
                if (length(mod$missing_datanames) > 1) "are missing" else "is missing",
                if (show_module_info) sprintf(" for tab '%s'.", mod$label) else "."
```

**Review by averissimo — CHANGES_REQUESTED** [review]
Messages are not equivalent in the ending `"Dataset available in data: ..."`

I suggested the fix and recommend adding the test in the bottom (or similar)

``` r
pkgload::load_all("teal")
#> You are using teal version 0.15.2.9078
mods <- modules(example_module(datanames = c("iris", "mtcars", "co2")))

check_modules_datanames(mods, "iris")
#> [1] "Datasets \"mtcars\", \"co2\" are missing for module \"example teal module\". Datasets available in data: \"iris\""

check_modules_datanames_html(mods, "iris") |> toString() |> rvest::read_html() |> rvest::html_text() |> stringr::str_replace_all(" ?\n ?", "")
#> [1] " Datasets mtcars  and co2 are missing for tab 'example teal module'. No datasets are available in data."
```

<sup>Created on 2024-10-28 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>


```r
testthat::test_that("check_modules_datanames result is equivalent in text and html format", {
  testthat::skip_if_not_installed("xml2")
  testthat::skip_if_not_installed("rvest")

  mods <- modules(
    example_module(datanames = c("iris", "mtcars", "co2"))
  )

  text_message <- check_modules_datanames(mods, "iris")
  html_message <- check_modules_datanames_html(mods, "iris")

  # Cleanup messages (making text_message the template/target)

  # remove quotes and backticks
  text_clean <- gsub("[\"'`]", "", text_message)
  html_clean <- gsub("[\"'`]", "", html_clean)

  # Cleanup extra spaces
  html_clean <- paste(
    collapse = " ",
    trimws(
      strsplit(
        rvest::html_text(rvest::minimal_html(html_message), trim = TRUE),
        "\n"
      )[[1]]
    )
  )

  # Replace " and " to ", " to be similar to text
  html_clean <- gsub(" and ", ", ", html_clean, fixed = TRUE)
  # Convert from UI's "tab" to warning's "module" to be similar to text warning
  html_clean <- gsub("are missing for tab", "are missing for module", html_clean, fixed = TRUE)
  # Replace singular to plural
  html_clean <- gsub("Dataset ", "Datasets ", html_clean)
  # Remove extra full stop in html
  html_clean <- gsub("[.]$", "", html_clean)

  # String should now be the same
  testthat::expect_identical(html_clean, text_clean)
})
```

File: R/utils.R [hunk 4]
```diff
@@ -122,76 +122,112 @@ report_card_template <- function(title, label, description = NULL, with_filter,
...
+#' @noRd
+to_html_code_list <- function(x) {
+  checkmate::assert_character(x)
+  do.call(
+    tagList,
+    lapply(seq_along(x), function(.ix) {
+      tagList(
+        tags$code(x[.ix]),
+        if (.ix != length(x)) {
+          tags$span(ifelse(.ix == length(x) - 1, " and ", ", "))
```
Comment (averissimo) [inline R/utils.R:223]: Minor suggestion so that commna `, ` doesn't appear with an extra space in text format.

```diff
---"Datasets `missing1` , `missing2` and `missing3` are missing for module 'example teal module'. Dataset available in data: `iris`."
+++"Datasets `missing1`, `missing2` and `missing3` are missing for module 'example teal module'. Dataset available in data: `iris`."
```

```suggestion
          if(.ix == length(x) - 1) tags$span(" and ") else tags$span(", ", .noWS = "before")
```

**Review by averissimo — APPROVED** [review]
Great work!

You made this manual conversion beautiful :100: 

I left one \*\***optional**\*\* (esthetics) suggestion that removes extra space before the commas.
