### PR TITLE
Fix (integration) tests

### LINKED ISSUE #1695: [Bug]: Integration tests fail
### What happened?

Integration tests failed:

- Capitalization changed
- Deprecation warning
- ui changed

```
  [ FAIL 3 | WARN 1 | SKIP 6 | PASS 719 ]
  
  ══ Skipped tests (6) ═══════════════════════════════════════════════════════════
  • need a fix in a .slicesGlobal (1): 'test-module_teal.R:1399:11'
  • todo (3): 'test-module_teal.R:1662:5', 'test-module_teal.R:1698:5',
    'test-module_teal.R:1701:5'
  • TODO (1): 'test-shinytest2-reporter.R:53:3'
  • todo: error (1): 'test-shinytest2-module_bookmark_manager.R:4:1'
  
  ══ Warnings ════════════════════════════════════════════════════════════════════
  ── Warning ('test-teal_reporter.R:2:3'): TealReportCard object can be initialized ──
  `ReportCard$new()` was deprecated in teal.reporter 0.6.0.
  ℹ Please use `teal_card()` instead.
  ℹ Use teal_report class instead. See vignette('teal-report-class',
    'teal.reporter') for more information.
  ℹ The deprecated feature was likely used in the R6 package.
    Please report the issue at <https://github.com/r-lib/R6/issues>.
  Backtrace:
       ▆
    1. ├─testthat::expect_no_error(TealReportCard$new()) at test-teal_reporter.R:2:3
    2. │ └─testthat:::expect_no_(...)
    3. │   └─testthat:::quasi_capture(enquo(object), NULL, capture)
    4. │     ├─testthat (local) .capture(...)
    5. │     │ ├─base::withRestarts(...)
    6. │     │ │ └─base (local) withOneRestart(expr, restarts[[1L]])
    7. │     │ │   └─base (local) doWithOneRestart(return(expr), restart)
    8. │     │ └─base::withCallingHandlers(...)
    9. │     └─rlang::eval_bare(quo_get_expr(.quo), quo_get_env(.quo))
   10. └─TealReportCard$new()
   11.   └─teal.reporter (local) initialize(...)
  
  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Failure ('test-shinytest2-filter_manager.R:14:3'): e2e: wunder_bar_srv clicking filter icon opens filter-manager modal ──
  Expected `app$get_text(".teal-filter-manager-modal")` to match regexp "Filter manager".
  Actual text:
  ✖ │ 
    │         
    │           Filter Manager
    │         
    │         
    │           
    │             
    │        No filters specified.  
    │     
    │         
    │       
  ── Failure ('test-shinytest2-init.R:18:3'): e2e: teal app initializes with no errors ──
  Snapshot of `file` has changed.
  
  Backtrace:
      ▆
   1. └─app$expect_screenshot(selector = "#teal-tabpanel_wrapper") at test-shinytest2-init.R:18:3
   2.   └─shinytest2:::app_expect_screenshot_and_variant(...)
   3.     └─shinytest2:::app_expect_screenshot(self, private, ...)
   4.       └─shinytest2:::app__expect_snapshot_file(...)
   5.         ├─base::withCallingHandlers(...)
   6.         └─testthat::expect_snapshot_file(...)
  ── Failure ('test-shinytest2-reporter.R:39:3'): e2e: reporter tab is visible when the teal ui creation is delayed ──
  Expected `unlist(...)` to be TRUE.
  Differences:
  `actual` is NULL
  `expected` is a logical vector (TRUE)
  
  
  ── Snapshots ───────────────────────────────────────────────────────────────────
  To review and process snapshots locally:
  * Download and unzip artifact.
  * Copy 'tests/testthat/_snaps' to local package.
  * Run `testthat::snapshot_accept()` to accept all changes.
  * Run `testthat::snapshot_review()` to review all changes.
  [ FAIL 3 | WARN 1 | SKIP 6 | PASS 719 ]
  Error:
  ! Test failures.
  Execution halted
```

### sessionInfo()

```R

```

### Relevant log output

```R

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [x] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [x] I agree to follow this project's Security Policy.

### PR DESCRIPTION
**Pull request by llrs-roche**
# Pull Request

Fixes #1695 in order to have checks all green on other PR

- [x] Capitalization changed
- [x] Deprecation warning
- [x] ui changed

### CODE REVIEW

File: tests/testthat/test-shinytest2-reporter.R [hunk 1]
```diff
@@ -36,6 +36,8 @@ testthat::test_that("e2e: reporter tab is visible when the teal ui creation is d
   )
 
   # Runs the same check as `app$is_visible` to check if the selector is visible
+  app$wait_js()
+  app$wait_for_page_stability()
```
Comment (donyunardi) [inline tests/testthat/test-shinytest2-reporter.R]: These two lines gave me an error when I run it locally

```r
r$> app$wait_js()
Error: attempt to apply non-function

r$> app$wait_for_page_stability()
Error: attempt to apply non-function
```

The `app` object that we use here is from `shinytest2::AppDriver` and `wait_for_page_stability()` is a method from `TealAppDriver`. I can't find out where `wait_js()` is coming from. 

Are you able to reproduce this?

Comment (llrs-roche) [reply tests/testthat/test-shinytest2-reporter.R]: I can reproduce it now, maybe when I wrote I mixed apps. Thanks for double checking.

Comment (llrs-roche) [reply tests/testthat/test-shinytest2-reporter.R]: I pushed a new commit that passes the checks on the .devcontainer so I hope it will pass on the integration tests too.
