### PR TITLE
870 some bugs@main

### LINKED ISSUE #870: Error in ui_tabs_with_filters: Assertion on 'datasets' failed: Must be of type 'list', not 'FilteredData/R6'
I am running examples in `R/module_tabs_with_filters.R` and experienced the error

```{R}
Listening on http://127.0.0.1:3914
Warning: Error in ui_tabs_with_filters: Assertion on 'datasets' failed: Must be of type 'list', not 'FilteredData/R6'.
  71: <Anonymous>
  70: stop
  69: mstop
  68: makeAssertion
  67: checkmate::assert_list
  66: ui_tabs_with_filters [C:/Rprojects/teal/R/module_tabs_with_filters.R#101]
  58: ui [#3]
   1: runApp
```

Looks like `ui_tabs_with_filters()` was updated during `filter_panel_refactor@main` merge (https://github.com/insightsengineering/teal/pull/851) in here with this assertion
https://github.com/insightsengineering/teal/commit/4bd3d4dce447679214062ce60cd1655ec8682746#diff-4f423e897518229b2c38ad4098fdad8652e2b43c340b28b8ad4ddeeeb05037a7R100-R101 and examples no longer work.

Below is the code I used to run the example on a function that is not exported

```{R}
library(teal)
devtools::load_all('.')
mods <- teal:::example_modules()
datasets <- teal:::example_datasets()

app <- shinyApp(
  ui = function() {
    tagList(
      teal:::include_teal_css_js(),
      textOutput("info"),
      fluidPage( # needed for nice tabs
        ui_tabs_with_filters("dummy", modules = mods, datasets = datasets)
      )
    )
  },
  server = function(input, output, session) {
    active_module <- srv_tabs_with_filters(
      id = "dummy",
      datasets = datasets,
      modules = mods,
      filter = NULL
    )
    output$info <- renderText({
      paste0("The currently active tab name is ", active_module()$label)
    })
  }
)
if (interactive()) {
  runApp(app)
}
```

### sessionInfo()

```R
Just run smooth staged.deps installation

```{R}
x <- staged.dependencies::dependency_table(".")
staged.dependencies::install_deps(x, upgrade = "always")
```

and the current session info is like below

```{R}
R version 4.3.0 (2023-04-21 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default


locale:
[1] LC_COLLATE=English_Europe.utf8  LC_CTYPE=English_Europe.utf8    LC_MONETARY=English_Europe.utf8
[4] LC_NUMERIC=C                    LC_TIME=English_Europe.utf8    

time zone: Europe/Berlin
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] teal_0.13.0.9010          testthat_3.1.10           teal.transform_0.3.0.9006 magrittr_2.0.3           
[5] teal.slice_0.3.0.9016     teal.data_0.2.0.9003      shiny_1.7.4.1            

loaded via a namespace (and not attached):
 [1] teal.reporter_0.1.1.9018 stringi_1.7.12           digest_0.6.31            evaluate_0.21           
 [5] grid_4.3.0               pkgload_1.3.2.1          fastmap_1.1.1            rprojroot_2.0.3         
 [9] processx_3.8.2           pkgbuild_1.4.0           sessioninfo_1.2.2        brio_1.1.3              
[13] backports_1.4.1          urlchecker_1.0.1         ps_1.7.5                 promises_1.2.0.1        
[17] purrr_1.0.1              cli_3.6.1                rlang_1.1.1              crayon_1.5.2            
[21] ellipsis_0.3.2           withr_2.5.0              remotes_2.4.2            cachem_1.0.8            
[25] yaml_2.3.7               devtools_2.4.5           tools_4.3.0              memoise_2.0.1           
[29] checkmate_2.2.0          httpuv_1.6.11            formatters_0.5.1.9000    teal.widgets_0.3.0.9004 
[33] vctrs_0.6.2              logger_0.2.2             R6_2.5.1                 mime_0.12               
[37] lifecycle_1.0.3          stringr_1.5.0            fs_1.6.2                 htmlwidgets_1.6.2       
[41] usethis_2.2.2            miniUI_0.1.1.1           fontawesome_0.5.1        shinyjs_2.1.0           
[45] desc_1.4.2               callr_3.7.3              teal.logger_0.1.1.9007   pkgdown_2.0.7           
[49] later_1.3.1              glue_1.6.2               profvis_0.3.8            Rcpp_1.0.10             
[53] xfun_0.39                knitr_1.43               rstudioapi_0.15.0        xtable_1.8-4            
[57] htmltools_0.5.5          rmarkdown_2.23           compiler_4.3.0           prettyunits_1.1.1 
```

### PR DESCRIPTION
**Pull request by chlebowa**
Fixes #870 

1. `example_datasets` is modified to return a nested list of `FilteredData` objects to match module tree generated by `example_modules`. 
2. `example_datasets` had `filters = "all"` and datanames here need to be enumerated explicitly. Resolve of `"all"` happens in `teal::init`
3. Isolated evaluation of reactives outside of reactive context
4. Merged documentation of `ui_` and `srv_` modules and inherited parameters instead of rewriting each time.

### CODE REVIEW

File: R/module_tabs_with_filters.R [hunk 1]
```diff
@@ -99,6 +99,11 @@
 ui_tabs_with_filters <- function(id, modules, datasets, filter) {
   checkmate::assert_class(modules, "teal_modules")
   checkmate::assert_list(datasets, types = c("list", "FilteredData"))
+  if (!missing(filter)) {
+    checkmate::assert_class(filter, "teal_slices")
+  } else {
+    filter <- teal_slices(module_specific = FALSE)
```
Comment (m7pr) [inline R/module_tabs_with_filters.R:105]: what about specifying default value for filter as `teal_slices(module_specific = FALSE)`? no strong opinion on it.
srv_tabs_with_filters has filter se to default value and this could be set to `teal_slices(module_specific = FALSE)` instead of NULL

**Comment by chlebowa** [comment]
Errors reported in #870 have been removed but a new one occurs.

Shockingly, it comes from the filter manager module, where the mapping matrix is accessed outside of a reactive context. I say shockingly because the filter manager was extensively tested during its implementation and this error was never raised.

### app that crashes
```
rm(list = ls())
devtools::load_all("../teal")
mods <- teal:::example_modules()
datasets <- teal:::example_datasets()

app <- shinyApp(
  ui = function() {
    tagList(
      teal:::include_teal_css_js(),
      textOutput("info"),
      fluidPage( # needed for nice tabs
        ui_tabs_with_filters("dummy", modules = mods, datasets = datasets)
      )
    )
  },
  server = function(input, output, session) {
    active_module <- srv_tabs_with_filters(
      id = "dummy",
      datasets = datasets,
      modules = mods
    )
    output$info <- renderText({
      paste0("The currently active tab name is ", active_module()$label)
    })
  }
)

runApp(app, launch.browser = TRUE)
```

### app that runs
```
library(teal.modules.general)
pkgload::load_all("../teal")

funny_module <- function (label = "Filter states", datanames = "all") {
  checkmate::assert_string(label)
  module(
    label = label,
    filters = datanames,
    ui = function(id, ...) {
      ns <- NS(id)
      div(
        h2("The following filter calls are generated:"),
        verbatimTextOutput(ns("filter_states")),
        verbatimTextOutput(ns("filter_calls")),
        actionButton(ns("reset"), "reset_to_default")
      )
    },
    server = function(input, output, session, data, filter_panel_api) {
      checkmate::assert_class(data, "tdata")
      observeEvent(input$reset, set_filter_state(filter_panel_api, default_filters))
      output$filter_states <-  renderPrint({
        logger::log_trace("rendering text1")
        filter_panel_api %>% get_filter_state()
      })
      output$filter_calls <- renderText({
        logger::log_trace("rendering text2")
        attr(data, "code")()
      })
    }
  )
}

default_filters <- teal::teal_slices(
  teal_slice("iris", "Sepal.Length"),
  teal_slice("iris", "Sepal.Width"),
  teal_slice("iris", "Species"),
  teal_slice("mtcars", "mpg"),
  exclude_varnames = list(
    iris = c("Petal.Length"),
    mtcars = c("qsec", "drat")
  ),
  module_specific = TRUE
)
app <- init(
  data = teal_data(
    dataset("iris", iris),
    dataset("mtcars", mtcars)
  ),
  modules = modules(
    tm_data_table(
      "table",
      variables_selected = list(),
      dt_args = list()
    ),
    modules(
      label = "tab1",
      funny_module("funny", datanames = NULL),
      funny_module("funny2", datanames = "iris")
    )
  ),
  filter = default_filters
)

runApp(app, launch.browser = TRUE)
```

File: R/module_tabs_with_filters.R (hunk 1 above)
Comment (chlebowa) [reply R/module_tabs_with_filters.R:105]: This function has no defaults at all.

Comment (m7pr) [reply R/module_tabs_with_filters.R:105]: wanna remove default value for filter in srv_tabs_with_filters for consistency then?

Comment (chlebowa) [reply R/module_tabs_with_filters.R:105]: No, those seem to be there for a reason. I could consider having `filter` like in the UI function but then the example has to be changed as well, which I don't want to do out of respect for the author. The way `reporter` is passed down the stack is shady and that default may be crucial.

Comment (m7pr) [reply R/module_tabs_with_filters.R:105]: I hear you

**Review by m7pr — APPROVED** [review]
Apps listed in @chlebowa comment are working now. Also the example runs smoothly. Thanks for the help
