### PR TITLE
1304 handover error@main

### LINKED ISSUE #1304: User experience for failures of teal_transform_module
### Summary

Currently, users can apply multiple `teal_transform_module` instances to a module.

If one of the `teal_transform_module` fails, the current behavior is as follows:
* Validation or assertion occurs to warn users that the transformation cannot be completed. In addition, the border box around the `teal_transform_module` will turn red to visually inform the user that the transformation failed to run.
* The data continues to be passed to the other `teal_transform_module` for processing.

To illustrate this, let's say a teal module has two `teal_transform_module` instances assigned to it:
1. The first `teal_transform_module` creates or mutates a new variable in a dataset.
2. The second `teal_transform_module` renames several values in a column.

If the first `teal_transform_module` fails, the app user can still execute the second `teal_transform_module`. This is the current behavior of our `teal_transform_module` feature.

The concern is that if the `teal_transform_module` represents sequential steps in generating a certain analysis for a teal module, it may not make sense to allow the user to execute the second `teal_transform_module` until the issue with the first one is resolved. By doing this, app users may be prevented from generating incorrect analyses or plots.

Then, what is better UX for failures in teal_transform_module?
1. Keep current behavior (ignore error from failing teal_transform_module and pass (unmodified) data further).
2. Prevent other `teal_transform_module` to run, if the first one fail, by passing error further. It will require adding req(data()) in all observeEvent and renderXyz added in teal_transform_module.

### PR DESCRIPTION
**Pull request by gogonzo**
Alternative solution to #1330. Closes #1304, #1307, and #1308

1. When teal_data_module fails, then teal-module-tabs are disabled. When teal_data_module returns teal_data again teal-module-tabs are enabled
2. When reactive data passed directly to srv_teal fails, then the whole tab-panel is hidden and error message is shown. Warning messages are displayed over tab-panel.
3. when teal_transform_module fails then following teal_transform_module(s) show generic message that something was wrong. Reason for this is the same as (3).
4. when teal_transform_module fails then teal-module output is disabled and generic failure message is shown in the main panel. We decided to show a generic failure message as "real failure message" should be only shown in the place where error occurred to no cause confusion.
5. failing teal_data_module/teal_transform_module fallbacks to previous valid data (see exaplanation below)

The most important part of the implementation is that when teal_data_module fails then it return the previous valid data (i.e. it return unchanged data). This means that failure doesn't trigger downstream reactivity and we don't need to deal with `data` input as error. In other words, this implementation halts reactivity when something goes wrong. 
When something goes wrong, teal-module-output is hidden and instead error message is displayed.

Also, I've moved `data` completely away from `ui` and now if there is `teal_data_module` then data-tab is added dynamically. 

<details>
<summary>app w/ teal_data_module</summary>

```r
options(
  teal.log_level = "TRACE",
  teal.show_js_log = TRUE,
  # teal.bs_theme = bslib::bs_theme(version = 5),
  shiny.bookmarkStore = "server"
)

# pkgload::load_all("teal.data")
pkgload::load_all("teal")

make_data <- function(datanames = c("ADSL", "ADTTE")) {
  data_obj <- teal.data::teal_data()
  if ("ADSL" %in% datanames) {
    data_obj <- within(data_obj, ADSL <- teal.data::rADSL)
  }
  if ("ADTTE" %in% datanames) {
    data_obj <- within(data_obj, ADTTE <- teal.data::rADTTE)
  }
  join_keys(data_obj) <- default_cdisc_join_keys[datanames]
  teal.data::datanames(data_obj) <- datanames
  data_obj
}

trans <- list(
  teal_transform_module(
    ui = function(id) {
      ns <- NS(id)
      tagList(
        selectizeInput(
          ns("errortype"),
          label = "Error Type",
          choices = c(
            "ok", "insufficient datasets", "no data",
            "qenv.error", "error in reactive", "validate error", "silent.shiny.error", "not a reactive"
          )
        )
      )
    },
    server = function(id, data) {
      moduleServer(id, function(input, output, session) {
        logger::log_trace("example_module_transform2 initializing.")
        reactive({
          switch(input$errortype,
            ok = data(),
            `insufficient datasets` = teal:::.subset_teal_data(data(), "ADSL"),
            `no data` = teal_data(),
            qenv.error = within(teal_data(), stop("\nthis is qenv.error in teal_transform_module\n")),
            `error in reactive` = stop("\nerror in a reactive in teal_transform_module\n"),
            `validate error` = validate(need(FALSE, "\nvalidate error in teal_transform_module\n")),
            `silent.shiny.error` = req(FALSE)
          )
        })
      })
    }
  )
)

data <- teal_data_module(
  once = FALSE,
  ui = function(id) {
    ns <- NS(id)
    tagList(
      selectizeInput(
        ns("errortype"),
        label = "Error Type",
        choices = c(
          "ok", "insufficient datasets", "no data",
          "qenv.error", "error in reactive", "validate error", "silent.shiny.error", "not a reactive"
        )
      ),
      actionButton(ns("submit"), "Go!")
    )
  },
  server = function(id, ...) {
    moduleServer(id, function(input, output, session) {
      logger::log_trace("example_module_transform2 initializing.")
      eventReactive(input$submit, {
        switch(input$errortype,
          ok = make_data(),
          `insufficient datasets` = make_data(datanames = "ADSL"),
          `no data` = teal_data(),
          qenv.error = within(data(), stop("\nthis is qenv.error in teal_data_module\n")),
          `error in reactive` = stop("\nerror in a reactive in teal_data_module\n"),
          `validate error` = validate(need(FALSE, "\nvalidate error in teal_data_module\n")),
          `silent.shiny.error` = req(FALSE)
        )
      })
    })
  }
)

app <- teal::init(
  data = data,
  modules = list(
    example_module("mod-1", transformers = c(trans, trans, trans), datanames = c("ADSL", "ADTTE")),
    example_module("mod-2", transformers = trans, datanames = c("ADSL", "ADTTE")),
    module(
      label = "I was made to annoy you",
      ui = function(id) NULL,
      server = function(id, data) {
        moduleServer(id, function(input, output, session) {
          observe({
            teal.data::datanames(data())
            ADSL <- data()[["ADSL"]]
            ADSL$AGE
          })

          observeEvent(data(), {
            print(data()[["ADSL"]]$SEX)
          })
        })
      },
      datanames = "ADSL"
    )
  ),
  filter = teal_slices(
    teal_slice("ADSL", "SEX"),
    teal_slice("ADSL", "AGE", selected = c(18L, 65L)),
    teal_slice("ADTTE", "PARAMCD", selected = "CRSD"),
    include_varnames = list(
      ADSL = c("SEX", "AGE")
    )
  )
)

runApp(app)

```

</details>

<details>
<summary>app wrapped</summary>

```r
options(
  teal.log_level = "TRACE",
  teal.show_js_log = TRUE,
  # teal.bs_theme = bslib::bs_theme(version = 5),
  shiny.bookmarkStore = "server"
)
library(scda)
pkgload::load_all("teal")

make_data <- function(datanames = c("ADSL", "ADTTE")) {
  data_obj <- teal.data::teal_data()
  if ("ADSL" %in% datanames) {
    data_obj <- within(data_obj, ADSL <- teal.data::rADSL)
  }
  if ("ADTTE" %in% datanames) {
    data_obj <- within(data_obj, ADTTE <- teal.data::rADTTE)
  }
  join_keys(data_obj) <- default_cdisc_join_keys[datanames]
  teal.data::datanames(data_obj) <- datanames
  data_obj
}

ui_data <- function(id) {
  ns <- NS(id)
  tagList(
    selectizeInput(
      ns("errortype"),
      label = "Error Type",
      choices = c(
        "ok", "insufficient datasets", "no data",
        "qenv.error", "error in reactive", "validate error", "silent.shiny.error", "not a reactive"
      )
    ),
    actionButton(ns("submit"), "Go!")
  )
}

srv_data <- function(id, ...) {
  moduleServer(id, function(input, output, session) {
    logger::log_trace("example_module_transform2 initializing.")
    eventReactive(input$submit, {
      switch(input$errortype,
        ok = make_data(),
        `insufficient datasets` = make_data(datanames = "ADSL"),
        `no data` = teal_data(),
        qenv.error = within(data(), stop("\nthis is qenv.error in teal_data_module\n")),
        `error in reactive` = stop("\nerror in a reactive in teal_data_module\n"),
        `validate error` = validate(need(FALSE, "\nvalidate error in teal_data_module\n")),
        `silent.shiny.error` = req(FALSE)
      )
    })
  })
}

modules <- modules(
  teal.modules.general::tm_data_table("Data Table"),
  example_module("Example Module", datanames = "ADTTE"),
  module(
    ui = function(id) {
      ns <- NS(id)
      tagList(
        tableOutput(ns("filter_summary"))
      )
    },
    server = function(id, datasets) {
      moduleServer(id, function(input, output, session) {
        output$filter_summary <- renderTable({
          datasets$get_filter_overview(datanames = datasets$datanames())
        })
      })
    }
  )
)

shinyApp(
  ui = function(request) {
    fluidPage(
      ui_data("data"),
      ui_teal(id = "teal", modules = modules)
    )
  },
  server = function(input, output, session) {
    data_rv <- srv_data("data", data = data, modules = modules)
    srv_teal(id = "teal", data = data_rv, modules = modules)
  }
)

```

</details>

### CODE REVIEW

File: R/module_nested_tabs.R [hunk 1]
```diff
@@ -263,7 +265,6 @@ srv_teal_module.teal_module <- function(id,
 
     trigger_module <- reactive({
       req(module_teal_data_validated())
-      req(filtered_teal_data())
```
Comment (m7pr) [inline R/module_nested_tabs.R:266]: @gogonzo when this is deleted I do not see data on the second module when I select the second module in a simple app

```r
app <- init(
  data = teal_data(iris = iris, mtcars = mtcars),
  modules = modules(example_module("Module 1"), example_module("Module 2"))
)

shinyApp(app$ui, app$server)

```

image

Comment (gogonzo) [reply R/module_nested_tabs.R:266]: You can revert this line. We can deal with this later this week

File: R/module_teal_data.R [hunk 2]
```diff
@@ -108,14 +98,16 @@ srv_validate_reactive_teal_data <- function(id, # nolint: object_length
   checkmate::assert_flag(validate_shiny_silent_error)
 
   moduleServer(id, function(input, output, session) {
-    data_rv <- reactive(tryCatch(data(), error = function(e) e))
+    data_rv <- reactive(tryCatch(data(), error = function(e) e)) # todo: can be removed as data is already try-catched
```
Comment (m7pr) [inline R/module_teal_data.R:101]: `srv_teal_data()` has `tryCatch` in the end. `srv_teal_data()` is used inside `srv_init_data`.

`srv_validate_reactive_teal_data` is used inside `srv_teal_module` and `srv_teal_data`.
`srv_teal_module` uses data that comes from `srv_init_data`. `srv_init_data` uses `srv_teal_data`. It is `srv_init_data` that has `tryCatch` in the end. 

So input to `srv_validate_reactive_teal_data` in `srv_teal_module` is tryCatch-ed but input to `srv_validate_reactive_teal_data` in `srv_teal_data` is not tryCatch-ed

Comment (m7pr) [reply R/module_teal_data.R:101]:
```
srv_teal_module <- function() {
  x <- srv_init_data() #input is tryCatch-ed
  srv_validate_reactive_teal_data(x)
}

srv_init_data <- function() {
   y <- srv_teal_data()
   tryCatch(y)
}

srv_teal_data <- function() {
   srv_validate_reactive_teal_data() #input is not tryCatched
}
```

Comment (gogonzo) [reply R/module_teal_data.R:101]: Hmm, we can figure out where exactly to put tryCatch to minimise this.

Comment (m7pr) [reply R/module_teal_data.R:101]: It's probably rather like if we have `tryCatch` in `srv_validate_reactive_teal_data` then we don't need a `tryCatch` in `srv_init_data` at the end

File: R/module_teal_data.R [hunk 3]
```diff
@@ -250,3 +219,33 @@ srv_check_shiny_warnings <- function(id, data, modules) {
...
+    res <- try(this(), silent = TRUE)
+    if (inherits(res, "teal_data")) {
+      logger::log_debug("{ label } evaluated successfully.")
+      res
+    } else {
+      logger::log_debug("{ label } failed, falling back to previous data.")
+      that()
+    }
+  })
+}
```
Comment (gogonzo) [inline R/module_teal_data.R:251]: I think that `.fallback_on_failure` could look differently. Previously it was used in a way that each stage has `.fallback_on_failure` `teal_data_module -> .fallback_on_failure -> teal_transform_module[1] -> .fallback_on_failure -> teal_transform_module[2] -> ...`
This meant that if `teal_transform_module[2]` failed it took data output from `teal_transform_module[1]`. If `teal_transform_module[2]` failed as well then `teal_data_module` output was rolled. We can talk more on a daily 👍 

```suggestion
.fallback_on_failure <- function(this, that, label) {
  assert_reactive(this)
  assert_reactive(that)
  checkmate::assert_string(label)
  out <- reactiveVal()
  observe({
    if (inherits(res, "teal_data")) {
      logger::log_debug("{ label } evaluated successfully.")
      shiny::isolate(out(this()))
    }
  })
  out
}
```

File: R/module_nested_tabs.R (hunk 1 above)
Comment (m7pr) [reply R/module_nested_tabs.R:266]: I think there is something off with `.observe_active_filter_changed` that returns `NULL` on `init` hence

```r
    filtered_teal_data <- srv_filter_data(
      "filter_panel",
      datasets = datasets,
      active_datanames = active_datanames,
      data_rv = data_rv,
      is_active = is_active
    )
```

returns error

File: R/module_teal_data.R (hunk 3 above)
Comment (m7pr) [reply R/module_teal_data.R:251]: Should 

```r
if (inherits(res, "teal_data") && !identical(this(), shiny::isolate(out()))) {
```

be 

```
if (inherits(that, "teal_data") && !identical(this(), shiny::isolate(out()))) {
```

so that `that` is used anywhere

File: .github/workflows/check.yaml [hunk 4]
```diff
@@ -10,6 +10,7 @@ on:
       - ready_for_review
     branches:
       - main
+      - 1304-handle-data-inputs@main
```
Comment (m7pr) [inline .github/workflows/check.yaml:13]: Remove before the merge

File: R/module_nested_tabs.R [hunk 5]
```diff
@@ -247,9 +292,9 @@ srv_teal_module.teal_module <- function(id,
         # wait for module_teal_data() to be not NULL but only once:
         ignoreNULL = TRUE,
         once = TRUE,
-        eventExpr = module_teal_data_validated(),
+        eventExpr = trigger_module(),
         handlerExpr = {
-          module_out(.call_teal_module(modules, datasets, module_teal_data_validated, reporter))
+          module_out(.call_teal_module(modules, datasets, module_teal_data, reporter))
```
Comment (m7pr) [inline R/module_nested_tabs.R:297]: Should `trigger_data` and later calls be dependent on `module_teal_data_validated` or `module_teal_data`?

File: .github/workflows/check.yaml (hunk 4 above)
Comment (m7pr) [inline .github/workflows/check.yaml:13]:
```suggestion
```

File: R/module_nested_tabs.R [hunk 6]
```diff
@@ -103,7 +115,17 @@ ui_teal_module.teal_module <- function(id, modules, depth = 0L) {
...
+            width = 9,
+            div(
+              div(
+                class = "teal_validated"
+                # todo: should error message be displayed here?
+              ),
+              ui_teal
+            ),
+            class = "teal_primary_col"
+          ),
```
Comment (m7pr) [inline R/module_nested_tabs.R:128]: revert the change. nothing is needed here. this div was extended to include `ui_validate_teal_data` that no longer exists
https://github.com/insightsengineering/teal/pull/1330/files#diff-f7278c16079bf8eeee343aba99b73c110c99d6cc705b7bcdbcc0df3c8bde35abR112
```suggestion
          column(width = 9, ui_teal, class = "teal_primary_col"),
```

File: R/module_teal.R [hunk 7]
```diff
@@ -184,22 +189,30 @@ srv_teal <- function(id, data, modules, filter = teal_slices()) {
       }
     )
 
-    data_rv <- srv_init_data("data", data = data, modules = modules, filter = filter)
+    init_data <- srv_init_data("data", data = data, modules = modules, filter = filter)
+    # srv_validate_qenv_error("qenv_error", init_data) # init_data is always fallbacked
+    # we missed other types of errors because SRV_init_daTA already replaced error with teal_data()
```
Comment (m7pr) [inline R/module_teal.R:194]:
```suggestion
```

File: R/module_teal_data.R [hunk 8]
```diff
@@ -18,15 +18,17 @@
 #' `teal` (observers in `srv_teal`) always waits to render an app until `reactive` `teal_data` is
 #' returned. If error 2-4 occurs, relevant error message is displayed to app user and after issue is
 #' resolved app will continue to run. `teal` guarantees that errors in a data don't crash an app
-#' (except error 1). This is possible thanks to `.fallback_on_failure` which returns input-data
-#' when output-data fails
+#' (except error 1). This is possible by catching the error and returning an empty `teal_data` object.
+#' The error message is displayed in the app and the module will eventually get an empty `teal_data`.
```
Comment (m7pr) [inline R/module_teal_data.R:22]: This part of the documentation is the remaining of the solution implemented by Vedha in [this PR](https://github.com/insightsengineering/teal/pull/1330/) but is no longer true and should be reverted.

File: R/module_teal_data.R [hunk 9]
```diff
@@ -53,14 +66,18 @@ srv_teal_data <- function(id,
                           data,
                           data_module,
                           modules = NULL,
-                          validate_shiny_silent_error = TRUE) {
+                          validate_shiny_silent_error = TRUE,
+                          failure_callback = function(data) {
+                            invisible(NULL)
+                          },
+                          is_transformer_failed = reactiveValues()) {
```
Comment (m7pr) [inline R/module_teal_data.R:73]:
```suggestion
                          is_transformer_failed = reactiveValues(FALSE)) {
```

File: R/module_teal_data.R [hunk 10]
```diff
@@ -53,14 +66,18 @@ srv_teal_data <- function(id,
...
   checkmate::assert_string(id)
   checkmate::assert_class(data_module, "teal_data_module")
   checkmate::assert_multi_class(modules, c("teal_modules", "teal_module"), null.ok = TRUE)
```
Comment (m7pr) [inline R/module_teal_data.R:76]: Should we add checks for `failure_callback` and `is_transformer_failed`?

```r
checkmate::assert_function(failure_callback)
checkmate::assert_class(is_transformer_failed, "reactivevalues")

```

File: R/module_teal_data.R [hunk 11]
```diff
@@ -74,19 +91,58 @@ srv_teal_data <- function(id,
...
+    out <- reactiveVal(NULL)
+    observeEvent(data_validated(), {
+      if (inherits(data_validated(), "teal_data")) {
+        is_transformer_failed[[id]] <- FALSE
+        if (!identical(data_validated(), out())) {
+          out(data_validated())
+        }
+      } else {
+        is_transformer_failed[[id]] <- TRUE
+      }
```
Comment (m7pr) [inline R/module_teal_data.R:103]: Maybe let's keep logging information the same way we had it before in `.failure_on_fallback`? I think this was useful

```suggestion
      if (inherits(data_validated(), "teal_data")) {
        is_transformer_failed[[id]] <- FALSE
        if (!identical(data_validated(), out())) {
          out(data_validated())
          logger::log_debug(sprintf("Data element '%s' for module '%s' evaluated successfully.", id, modules$label))
        }
      } else {
        is_transformer_failed[[id]] <- TRUE
        logger::log_debug(sprintf("Data element '%s' for module '%s' failed. Falling back to previous data.", id, modules$label))
      }
```

File: R/module_teal_data.R [hunk 12]
```diff
@@ -43,8 +45,19 @@ ui_teal_data <- function(id, data_module) {
...
+      id = ns("wrapper"),
+      data_module$ui(id = ns("data"))
+    ),
+    div(
+      id = ns("input_error"),
+      class = "teal_validated",
+      uiOutput(ns("error"))
+    ),
+    div(
+      id = ns("wrapper_validate"),
```
Comment (m7pr) [inline R/module_teal_data.R:58]: New proposition for `wrapper_validate` name

- `data_validate`
- `input_validate`
- `teal_data_validate`

If we change this name in here also adjust `shinyjs::hide("wrapper_validate")` and `shinyjs::show("wrapper_validate")` in the code

File: R/module_teal_data.R [hunk 13]
```diff
@@ -100,109 +156,123 @@ srv_validate_reactive_teal_data <- function(id, # nolint: object_length
   checkmate::assert_flag(validate_shiny_silent_error)
 
   moduleServer(id, function(input, output, session) {
-    data_out_r <- reactive(tryCatch(data(), error = function(e) e))
+    # tryCatch can not be removed since in srv_teal_data this module works on non tryCatch-ed data
```
Comment (m7pr) [inline R/module_teal_data.R:159]:
```suggestion
```

File: R/module_teal_data.R [hunk 14]
```diff
@@ -100,109 +156,123 @@ srv_validate_reactive_teal_data <- function(id, # nolint: object_length
...
+    data_rv <- reactive(tryCatch(data(), error = function(e) e))
+    # there is an empty reactive cycle on init!
```
Comment (m7pr) [inline R/module_teal_data.R:161]:
```suggestion
    # there is an empty reactive cycle on `init` and `data_rv` has `shiny.silent.error` class
```

File: R/module_teal_data.R [hunk 15]
```diff
@@ -100,109 +156,123 @@ srv_validate_reactive_teal_data <- function(id, # nolint: object_length
...
-                collapse = "\n"
-              )
-            )
-          )
+          data()$message
         }
+        validate(
+          need(
+            FALSE,
+            sprintf("Shiny error when executing the `data` module\n%s", msg)
```
Comment (m7pr) [inline R/module_teal_data.R:196]:
```suggestion
            sprintf("Shiny error when executing the `data` module.\n%s", msg)
```

File: R/module_teal_data.R [hunk 16]
```diff
@@ -100,109 +156,123 @@ srv_validate_reactive_teal_data <- function(id, # nolint: object_length
...
         need(
-          checkmate::test_class(data_out, "teal_data"),
-          paste0(
-            "Assertion on return value from the 'data' module failed:",
-            checkmate::test_class(data_out, "teal_data"),
-            "Check your inputs or contact app developer if error persists.",
-            collapse = "\n"
-          )
+          inherits(data(), c("teal_data", "error")),
+          "Did not recieve a valid `teal_data` object. Cannot proceed further."
```
Comment (m7pr) [inline R/module_teal_data.R:246]: Let's remove `a valid`. It's ambiguous. We had `valid` in here where this check also checked `datanames` and `emptiness`. Now it checks only class. Also there was a typo in `receive`.
```suggestion
          "Did not receive `teal_data` object. Cannot proceed further."
```

File: R/module_transform_data.R [hunk 17]
```diff
@@ -68,17 +68,22 @@ srv_transform_data <- function(id, data, transforms, modules) {
 
   moduleServer(id, function(input, output, session) {
     logger::log_debug("srv_teal_data_modules initializing.")
-    Reduce(
+    is_transformer_failed <- reactiveValues()
+    transformed_data <- Reduce(
```
Comment (m7pr) [inline R/module_transform_data.R:72]:
```suggestion
    Reduce(
```

File: R/module_transform_data.R [hunk 18]
```diff
@@ -68,17 +68,22 @@ srv_transform_data <- function(id, data, transforms, modules) {
...
+          modules = modules,
+          failure_callback = failure_callback,
+          is_transformer_failed = is_transformer_failed
         )
       },
       x = names(transforms),
       init = data
     )
+
+    transformed_data
```
Comment (m7pr) [inline R/module_transform_data.R:87]:
```suggestion
```

File: R/module_transform_data.R (hunk 17 above)
Comment (m7pr) [reply R/module_transform_data.R:72]: This goes together with this https://github.com/insightsengineering/teal/pull/1341/files#r1756590831

File: R/utils.R [hunk 19]
```diff
@@ -381,3 +384,31 @@ build_datanames_error_message <- function(label = NULL,
...
+  shinyjs::disable(selector = sprintf(".teal-body:has('#%s') .nav li a", ns("options_buttons")))
+  if (hide_content) {
+    shinyjs::runjs(
+      sprintf(
+        '$("#%s .tab-content").hide()',
+        ns("tabpanel_wrapper")
+      )
+    )
+  }
+}
```
Comment (m7pr) [inline R/utils.R:398]: Would this be more understandable (R-wide) if `shinyjs::runjs( ***  .hide())` is replaced with `shinyjs::hide()`?

File: R/module_teal_data.R (hunk 11 above)
Comment (m7pr) [reply R/module_teal_data.R:103]: 👍 edited the suggestion

**Comment by m7pr** [comment]
Left a couple of small cosmetic comments and fixed conflicts with the main branch. Will now verify if the tests are passing or should we adjust them, since we edited some error/warning messages.

File: R/module_init_data.R [hunk 20]
```diff
@@ -69,55 +69,29 @@ srv_init_data <- function(id, data, modules, filter = teal_slices()) {
...
-      is_filter_ok <- check_filter_datanames(filter, .teal_data_ls(data_validated()))
-      if (!isTRUE(is_filter_ok)) {
-        showNotification(
-          "Some filters were not applied because of incompatibility with data. Contact app developer.",
-          type = "warning",
-          duration = 10
-        )
-        warning(is_filter_ok)
-      }
-    })
```
Comment (m7pr) [inline R/module_init_data.R:119]: This removal ended up in this fail of the test

```r
  `actual`:   TRUE 
  `expected`: FALSE
  ── Failure ('test-shinytest2-teal_data_module.R:167:3'): e2e: teal_data_module gets removed after successful data load, when once = TRUE ──
  app$is_visible(sprintf("#%s", submit)) is not FALSE
```

Should we bring this code back so that `teal_data_module` is hidden for `once` set to `TRUE`?

Comment (gogonzo) [reply R/module_init_data.R:119]: Yes, but only the part responsible for `once`

Comment (m7pr) [reply R/module_init_data.R:119]: 2 tests are failing for this

```r
Failure (test-shinytest2-teal_data_module.R:163:3): e2e: teal_data_module gets removed after successful data load, when once = TRUE
app$is_visible("#teal-teal_modules-active_tab a[data-value=\"teal_data_module\"]") is not FALSE

`actual`:   TRUE 
`expected`: FALSE

Failure (test-shinytest2-teal_data_module.R:167:3): e2e: teal_data_module gets removed after successful data load, when once = TRUE
app$is_visible(sprintf("#%s", submit)) is not FALSE

`actual`:   TRUE 
`expected`: FALSE


```

**Comment by m7pr** [comment]
2 tests failing for once=TRUE/FALSE parameter (because we removed an observer that is triggered to remove the `teal_data_module` after the click for `once = TRUE`. 2 more tests failing because we no longer return warnings for unknown filters

```r
── Failed tests ───────────────────────────────────────────────────────────────────
Failure (test-module_teal.R:1297:11): returns global filters with active=true, inactive=false, unavailable=na
`session$setInputs(`teal_modules-active_tab` = "module_1")` did not produce any warnings.
Backtrace:
     ▆
  1. ├─shiny::testServer(...) at test-module_teal.R:1280:7
  2. │ ├─shiny:::withMockContext(...)
  3. │ │ ├─shiny::isolate(...)
  4. │ │ │ ├─shiny::..stacktraceoff..(...)
  5. │ │ │ └─ctx$run(...)
  6. │ │ │   ├─promises::with_promise_domain(...)
  7. │ │ │   │ └─domain$wrapSync(expr)
  8. │ │ │   ├─shiny::withReactiveDomain(...)
  9. │ │ │   │ └─promises::with_promise_domain(...)
 10. │ │ │   │   └─domain$wrapSync(expr)
 11. │ │ │   │     └─base::force(expr)
 12. │ │ │   └─env$runWith(self, func)
 13. │ │ │     └─shiny (local) contextFunc()
 14. │ │ │       └─shiny::..stacktraceon..(expr)
 15. │ │ ├─shiny::withReactiveDomain(...)
 16. │ │ │ └─promises::with_promise_domain(...)
 17. │ │ │   └─domain$wrapSync(expr)
 18. │ │ │     └─base::force(expr)
 19. │ │ └─withr::with_options(...)
 20. │ │   └─base::force(code)
 21. │ └─rlang::eval_tidy(quosure, mask, rlang::caller_env())
 22. └─testthat::expect_warning(...) at test-module_teal.R:1297:11

Failure (test-module_teal.R:1333:11): returns column per module with active=true, inactive=false, unavailable=na
`session$setInputs(`teal_modules-active_tab` = "module_1")` did not produce any warnings.
Backtrace:
```

File: R/module_teal_data.R (hunk 10 above)
Comment (gogonzo) [reply R/module_teal_data.R:74]: yes

File: R/utils.R (hunk 19 above)
Comment (gogonzo) [reply R/utils.R:401]: @vedhav WDYT?

File: R/module_teal_data.R (hunk 8 above)
Comment (m7pr) [reply R/module_teal_data.R]: Fixed with https://github.com/insightsengineering/teal/pull/1341/commits/4cf27304ddd8f3ddf0746bd2c829ff822fff8c3a

File: R/utils.R [hunk 21]
```diff
@@ -381,3 +384,31 @@ build_datanames_error_message <- function(label = NULL,
...
+      '$("#%s .tab-content").show()',
+      ns("tabpanel_wrapper")
+    )
+  )
+  shinyjs::runjs(
+    sprintf(
+      '$("#%s .tab-content").trigger("shown");',
+      ns("tabpanel_wrapper")
+    )
+  )
```
[the remark this answers is not in the document]
Comment (gogonzo) [reply R/utils.R:416]: I think nothing. `.trigger("shown")` is the `shiny` method to retrigger calculation. It is useful for elements which have been hidden and their `renderXYZ` have been disabled because of being in the hidden state. Normally `shinyjs::hide` and `shinyjs::show` do their job. But if you're hiding html-elements containing shiny outputs with pure javascript code, then you need `.trigger("shown")`. Is that right @vedhav ?

**Comment by m7pr** [comment]
I see one more error. Warnings are not displayed for (empty data an insufficient datanames) when there is only one transformer

image


but are displayed if there is two or 3 transformers

image

File: R/module_teal_data.R (hunk 10 above)
Comment (m7pr) [reply R/module_teal_data.R:74]: https://github.com/insightsengineering/teal/pull/1341/commits/a532670d911dff4a850740f27b02ce16ba437380

File: R/module_init_data.R (hunk 20 above)
Comment (m7pr) [reply R/module_init_data.R]: https://github.com/insightsengineering/teal/pull/1341/commits/8265176a4f6376278cb4ab87b10a58f5bdc4754d

**Comment by m7pr** [comment]
After bringing back the removal of observer for `teal_data_module` case with `once=TRUE` we are just left with 2 failing tests https://github.com/insightsengineering/teal/pull/1341/commits/8265176a4f6376278cb4ab87b10a58f5bdc4754d

File: R/module_init_data.R [hunk 22]
```diff
@@ -133,8 +127,13 @@ srv_init_data <- function(id, data, modules, filter = teal_slices()) {
       )
     })
 
-    # Adds signature protection to the datanames in the data
-    reactive(.add_signature_to_data(data_validated()))
+    reactive({
+      if (inherits(data_validated(), "teal_data")) {
+        .add_signature_to_data(data_validated())
+      } else {
+        data_validated() # error, qenv.error, shiny.silent.error, validate-error
```
Comment (gogonzo) [inline R/module_init_data.R:134]: Not true anymore. It is `NULL` (initially if `teal_data` is unevaluated `teal_data_module`) or `teal_data`
```suggestion
        data_validated()
```

**Comment by gogonzo** [comment]
PR doesn't fix #1307 and #1308

<details>
<summary>app wrapped</summary>

```r
options(
  teal.log_level = "TRACE",
  teal.show_js_log = TRUE,
  # teal.bs_theme = bslib::bs_theme(version = 5),
  shiny.bookmarkStore = "server"
)
library(scda)
pkgload::load_all("teal")

ui_data <- function(id) {
  ns <- NS(id)
  tagList(
    selectizeInput(
      ns("errortype"),
      label = "Error Type",
      choices = c(
        "ok", "insufficient datasets", "no data",
        "qenv.error", "error in reactive", "validate error", "silent.shiny.error", "not a reactive"
      )
    ),
    actionButton(ns("submit"), "Go!")
  )
}

srv_data <- function(id, ...) {
  moduleServer(id, function(input, output, session) {
    logger::log_trace("example_module_transform2 initializing.")
    eventReactive(input$submit, {
      switch(input$errortype,
        ok = make_data(),
        `insufficient datasets` = make_data(datanames = "ADSL"),
        `no data` = teal_data(),
        qenv.error = within(data(), stop("\nthis is qenv.error in teal_data_module\n")),
        `error in reactive` = stop("\nerror in a reactive in teal_data_module\n"),
        `validate error` = validate(need(FALSE, "\nvalidate error in teal_data_module\n")),
        `silent.shiny.error` = req(FALSE)
      )
    })
  })
}

modules <- modules(
  teal.modules.general::tm_data_table("Data Table"),
  example_module("Example Module", datanames = "ADTTE"),
  module(
    ui = function(id) {
      ns <- NS(id)
      tagList(
        tableOutput(ns("filter_summary"))
      )
    },
    server = function(id, datasets) {
      moduleServer(id, function(input, output, session) {
        output$filter_summary <- renderTable({
          datasets$get_filter_overview(datanames = datasets$datanames())
        })
      })
    }
  )
)

shinyApp(
  ui = function(request) {
    fluidPage(
      ui_data("data"),
      ui_teal(id = "teal", modules = modules)
    )
  },
  server = function(input, output, session) {
    data_rv <- srv_data("data", data = data, modules = modules)
    srv_teal(id = "teal", data = data_rv, modules = modules)
  }
)

```

</details>

File: R/module_transform_data.R [hunk 23]
```diff
@@ -44,37 +44,34 @@ ui_transform_data <- function(id, transforms, class = "well") {
...
   )
 }
 
 #' @rdname module_transform_data
-srv_transform_data <- function(id, data, transforms, modules) {
+srv_transform_data <- function(id, data, transforms, modules, is_transformer_failed = reactiveValues()) {
   checkmate::assert_string(id)
   assert_reactive(data)
   checkmate::assert_list(transforms, "teal_transform_module", null.ok = TRUE)
   checkmate::assert_class(modules, "teal_module")
```
Comment (m7pr) [inline R/module_transform_data.R:59]:
```suggestion
  checkmate::assert_class(modules, "teal_module")
  checkmate::assert_class(is_transformer_failed, "reactivevalues")
```

File: R/module_filter_data.R [hunk 24]
```diff
@@ -92,3 +92,12 @@ srv_filter_data <- function(id, datasets, active_datanames, data_rv, is_active)
 
   trigger_data
 }
+
+#' @rdname module_filter_data
+.get_filter_expr <- function(datasets, datanames) {
```
Comment (gogonzo) [inline R/module_filter_data.R:97]: needed to handle empty `datanames` - when `teal_data` without objects is submitted

**Comment by m7pr** [comment]
Hey, just checked the current state of the PR and I don't see a warning for `no data` nor `insufficient datanames`, only 

> "Some filters were not applied because of incompatibility with data. Contact app developer."

for cases where data is selected of that type, or a transformer is selected of that type. Is that intended?

image

image


I suspect `check_modules_datanames()` is implemented improperly right now, after changes in `modules$datanames`  were introduced in https://github.com/insightsengineering/teal/pull/1344

File: R/module_teal_data.R [hunk 25]
```diff
@@ -38,171 +37,216 @@
...
-    output$shiny_warnings <- renderUI({
-      if (inherits(data_out_r(), "teal_data")) {
-        is_modules_ok <- check_modules_datanames(modules = modules, datanames = .teal_data_ls(data_validated()))
+#' @keywords internal
+srv_check_shiny_warnings <- function(id, data, modules) {
+  checkmate::assert_string(id)
+  moduleServer(id, function(input, output, session) {
+    output$message <- renderUI({
+      if (inherits(data(), "teal_data")) {
+        is_modules_ok <- check_modules_datanames(modules = modules, datanames = .teal_data_ls(data()))
```
Comment (m7pr) [inline R/module_teal_data.R:225]: Now, after https://github.com/insightsengineering/teal/pull/1344 got merged, `modules$datanames = 'all'`.
Previously it would be `modules$datanames = c('ADTTE', 'ADSL', 'all')` for the case where we had at least 2 transformers. 

For the cases where `datanames` is anything (e.g. `"ADSL"`) the check in `check_modules_datanames` that verifies the discrepancy between those two https://github.com/insightsengineering/teal/blob/af5eb40f515f6be941ab05a014e1da9c43e28165/R/utils.R#L148
does not find inconsistency between `'all'` and `"ADSL"`.

```r
modules <- list(datanames = "all")
datanames <- "ADSL"

(extra_datanames <- setdiff(modules$datanames, c("all", datanames)))
#> character(0)
```

**Comment by gogonzo** [comment]
> Hey, just checked the current state of the PR and I don't see a warning for `no data` nor `insufficient datanames`, only

I can see the warnings. Did you click the button?

> > "Some filters were not applied because of incompatibility with data. Contact app developer."
> for cases where data is selected of that type, or a transformer is selected of that type. Is that intended?

Please clarify, I don't understand.

File: R/module_nested_tabs.R [hunk 26]
```diff
@@ -20,6 +20,13 @@
 #'  When `datasets` is passed from the parent module (`srv_teal`) then `dataset` is a singleton
 #'  which implies in filter-panel to be "global". When `NULL` then filter-panel is "module-specific".
 #'
+#' @param status (`reactive` returning `character`)
+#'  Determines action dependent on a data loading status:
+#'  - `"ok"` when `teal_data` is returned from a data loading.
+#'  - `"disable"` when [teal_data_module()] didn't returned a `teal_data`. Disables tabs buttons
+#'  - `"hide"` when a `reactive` passed to `srv_teal(data)` didn't returned a `teal_data`. Hides the whole tabs
```
Comment (m7pr) [inline R/module_nested_tabs.R:27]:
```suggestion
#'  - `"ok"` when `teal_data` is returned from the data loading.
#'  - `"disable"` when [teal_data_module()] didn't return  `teal_data`. Disables tabs buttons.
#'  - `"hide"` when a `reactive` passed to `srv_teal(data)` didn't return `teal_data`. Hides the whole tabs
```

File: R/module_teal.R [hunk 27]
```diff
@@ -22,6 +22,13 @@
 #' - data filtering in [`module_filter_data`]
 #' - data transformation in [`module_transform_data`]
 #'
+#' ## Fallback on failure
+#'
+#' `teal` is designed in such way that app will never crash if the error is introduced in any
+#' custom module provided by app developer (e.g. [teal_data_module()], [teal_transform_module()]).
+#' If any module returns a failing object, the app will halt the evaluation and display a warning message.
+#' App user should always have a chance to fix wrong input and continue to avoid session's restart.
```
Comment (m7pr) [inline R/module_teal.R:30]:
```suggestion
#' App user should always have a chance to fix the improper input and continue without restarting the session.
```

File: R/module_teal.R [hunk 28]
```diff
@@ -184,33 +187,81 @@ srv_teal <- function(id, data, modules, filter = teal_slices()) {
...
+
+    status <- reactive({
+      if (inherits(data_pulled(), "teal_data")) {
+        "ok"
+      } else if (inherits(data, "teal_data_module")) {
+        "disable"
+      } else {
+        "hide"
+      }
+    })
```
Comment (m7pr) [inline R/module_teal.R:219]: The only thing that is a bit confusing, and the thing I need to rethink once more is why we use `data_pulled()` in here, where we also have `data_validated` and `data_init` build upon it. I guess instead of `data_pulled()` we could use `data_init()`?

Comment (gogonzo) [reply R/module_teal.R:219]: - `data_pulled` can return error
- `data_validated` always returns `teal_data` (after being NULL initially)
- `data_init` is `teal_data` with hashes in the `@code` (`.add_signature_to_data` )

**Comment by m7pr** [comment]
> > Hey, just checked the current state of the PR and I don't see a warning for no data nor insufficient datanames, only

> I can see the warnings. Did you click the button?

I did : P I don't see them

> > "Some filters were not applied because of incompatibility with data. Contact app developer."
> > for cases where data is selected of that type, or a transformer is selected of that type. Is that intended?

> Please clarify, I don't understand.

I only see a notification in the bottom right corner, but not a warning on the top left part of the app (in case of teal_data_module) and no warning inside transformer UI (in case for teal_transform_module).

**Comment by gogonzo** [comment]
> I only see a notification in the bottom right corner, but not a warning on the top left part of the app (in case of teal_data_module) and no warning inside transformer UI (in case for teal_transform_module).

This is a warning for filters which are not applied (`teal_slice` for datasets which don't exist). Errors on top are related to the modules$datanames.

File: R/module_teal_data.R (hunk 25 above)
Comment (gogonzo) [reply R/module_teal_data.R:225]: I've created an issue for this https://github.com/insightsengineering/teal/issues/1347 
Issue wasn't introduced in this PR and can be addresses anytime (@donyunardi will decide when)

Comment (m7pr) [reply R/module_teal_data.R:225]: Ok, so besides this one issue, the PR is solid rock.

File: R/module_teal.R [hunk 29]
```diff
@@ -22,6 +22,13 @@
 #' - data filtering in [`module_filter_data`]
 #' - data transformation in [`module_transform_data`]
 #'
+#' ## Fallback on failure
+#'
+#' `teal` is designed in such way that app will never crash if the error is introduced in any
+#' custom module provided by app developer (e.g. [teal_data_module()], [teal_transform_module()]).
```
Comment (vedhav) [inline R/module_teal.R:28]: With the shiny module and teal module being referred as module it becomes a little ambiguous. And, I think `teal_data_module` and `teal_transform_module` are exhaustive. Example could indicate that this is a non-exhaustive.

```suggestion
#' custom shiny module provided by app developer ([teal_data_module()] or [teal_transform_module()])
```

File: R/module_teal.R [hunk 30]
```diff
@@ -184,33 +186,91 @@ srv_teal <- function(id, data, modules, filter = teal_slices()) {
...
+          )
+        )
+      )
+
+      if (attr(data, "once")) {
+        observeEvent(data_rv(), once = TRUE, {
+          logger::log_debug("srv_teal@2 removing data tab.")
+          # when once = TRUE we pull data once and then remove data tab
+          removeUI(selector = sprintf("#%s a[data-value='teal_data_module']", session$ns("teal_modules-wrapper")))
+          updateTabsetPanel(inputId = "teal_modules-active_tab", selected = names(modules$children)[1])
```
Comment (vedhav) [inline R/module_teal.R:249]: I like the change of inserting the `teal_data_module` tab, we can use the same logic to remove it. This will be replaced by `nav_insert()` and `nav_remove()` when we move to `bslib`.
Also, the `updateTabsetPanel` was used because we needed to trigger the selection binding for shiny, since we removed using `removeUI` before, it was not happening.
```suggestion
          shiny::removeTab(
            "teal_modules-active_tab",
            target = "teal_data_module"
          )
```

File: R/module_teal_data.R [hunk 31]
```diff
@@ -16,17 +16,16 @@
...
+#' (except error 1).
 #'
 #' @param id (`character(1)`) Module id
 #' @param data (`reactive teal_data`)
 #' @param data_module (`teal_data_module`)
 #' @param modules (`teal_modules` or `teal_module`) For `datanames` validation purpose
 #' @param validate_shiny_silent_error (`logical`) If `TRUE`, then `shiny.silent.error` is validated and
+#' @param is_transformer_failed (`reactiveValues`) that hosts `logical` flags of which transformers failed
 #' error message is displayed.
 #' Default is `FALSE` to handle empty reactive cycle on `init`.
```
Comment (vedhav) [inline R/module_teal_data.R:30]: 1. Please also include param doc for `hide_validation_error`
2. I think the param of `is_transformer_failed` was inserted in the middle of the param doc of `is_transformer_failed`.
3. doc for `is_transformer_failed` seems incomplete. We can write a little more: the index of this list of boolean is the `id` so it is easy for people to know before seeing the code.
4. The param `data_module` should be renamed to something more meaningful. For the `ui_teal_data` it takes the module UI function and for the `srv_teal_data` it takes the module server function. Perhaps it should be `data_module_ui` and `data_module_srv`

File: R/module_teal_data.R [hunk 32]
```diff
@@ -38,174 +37,216 @@
...
+  out <- reactiveVal(NULL)
+  observeEvent(data(), {
+    if (inherits(data(), "teal_data")) {
+      if (!identical(data(), out())) {
+        out(data())
+      }
     } else {
-      logger::log_debug("{ label } failed, falling back to previous data.")
-      that()
     }
```
Comment (vedhav) [inline R/module_teal_data.R:248]: We can remove the empty else statement.

**Review by vedhav — COMMENTED** [review]
Great work 💪🏽 The error handling is robust and I really clear distinction between the init data and data during transform.
The `data_load_status` for init data and `is_transformer_failed` for data transforms a good way to manage what is happening.
The show/disable/hide logic living inside nested tabs makes sense 👍🏽 

I just have minor comments and we can merge this.

**Review by vedhav — APPROVED** [review]
Works like a charm 🎉

**Comment by m7pr** [comment]
🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥
